config/routes.rb
Rails.application.routes.draw do

 resources :recipes

end

app/models/categories_recipe.rb
class CategoriesRecipe < ActiveRecord::Base
end

app/models/categories_recipes.rb
class CategoriesRecipes < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
 belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
   
   mount_uploader :attachment, AttachmentUploader
   validates :description, :nickname, :title, :ingredients, :instructions, :category_ids, presence: true

 has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
  class CategoriesController < ApplicationController
 
  def index
    @categories = Category.all
    end
  end

  def show
    @category = Category.find(params[:id])
    end
  end

  
  def new
    @category = Category.new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

 
  def create
    @category = Category.new(params[:category])
  end

 
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipes_url
    else
      render:new
  end
end

def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update_attributes(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:nickname, :website, :instagram, :title, :description, :instructions, :ingredients, :notes, :embed, :photo, :category_ids, :attachment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mixi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>

 <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :instagram %><br />
    <%= f.text_area :instagram %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br />
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :embed %><br />
    <%= f.text_area :embed %>
  </div>
   <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_area :photo %>
  </div>
  <div class="field">
   <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    </div>
  <div class="field">

<%= f.collection_select :category_ids, Category.all, :id, :name, :prompt => "Select a category" %>

</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>edit recipe</h1>

<%= render 'form' %>

 <%= link_to "Delete recipe", @recipe, method: :delete, data: {confirm: "Are you sure you want to permanently remove this recipe from Mixi?"} %> |

<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>

<% @recipes.each do |recipe| %>
 <li><%= link_to "#{recipe.title}", recipe_path(recipe) %>
 </li>

  <% end %>

app/views/recipes/new.html.erb
<h1>Submit a recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %> </h1> <p>
Submitted by <%= @recipe.nickname %>  <p>
<%= @recipe.photo %> <p>
<%= @recipe.description %> <p>
<%= @recipe.ingredients %> <p>
<%= @recipe.instructions %> <p>
<%= @recipe.notes %> <p>
<%= @recipe.embed %> <p>
<%= @recipe.category_ids%><p>
<%= image_tag @recipe.attachment %>
<p>
<%= link_to "Edit Recipe", edit_recipe_path(@recipe) %>